POST  http://localhost:3003/api/blogs/
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGUiLCJpZCI6IjVmMzJhMWZlYjczMDliM2Q2ODNlYWY2ZSIsImlhdCI6MTU5NzIyNDI3Mn0.SNEuxKCilz6_1_SnhcB0hZGtznMC2f3Gj84iMxMFy28

{
    "likes": 11,
    "title": "Turun saksi maailma",
    "author": "Panu Aukko",
    "url": "www.loytyykohan.fi"
}